// path: src/store/ExtraServices/actionTypes.js
export const FETCH_EXTRA_SERVICES = "FETCH_EXTRA_SERVICES";
export const FETCH_EXTRA_SERVICES_SUCCESS = "FETCH_EXTRA_SERVICES_SUCCESS";
export const FETCH_EXTRA_SERVICES_FAIL = "FETCH_EXTRA_SERVICES_FAIL";

export const FETCH_EXTRA_SERVICE = "FETCH_EXTRA_SERVICE";
export const FETCH_EXTRA_SERVICE_SUCCESS = "FETCH_EXTRA_SERVICE_SUCCESS";
export const FETCH_EXTRA_SERVICE_FAIL = "FETCH_EXTRA_SERVICE_FAIL";

export const CREATE_EXTRA_SERVICE = "CREATE_EXTRA_SERVICE";
export const CREATE_EXTRA_SERVICE_SUCCESS = "CREATE_EXTRA_SERVICE_SUCCESS";
export const CREATE_EXTRA_SERVICE_FAIL = "CREATE_EXTRA_SERVICE_FAIL";

export const UPDATE_EXTRA_SERVICE = "UPDATE_EXTRA_SERVICE";
export const UPDATE_EXTRA_SERVICE_SUCCESS = "UPDATE_EXTRA_SERVICE_SUCCESS";
export const UPDATE_EXTRA_SERVICE_FAIL = "UPDATE_EXTRA_SERVICE_FAIL";

export const DELETE_EXTRA_SERVICE = "DELETE_EXTRA_SERVICE";
export const DELETE_EXTRA_SERVICE_SUCCESS = "DELETE_EXTRA_SERVICE_SUCCESS";
export const DELETE_EXTRA_SERVICE_FAIL = "DELETE_EXTRA_SERVICE_FAIL";