// path: src/store/TransportationSizes/actionTypes.js
export const FETCH_TRANSPORTATION_SIZES = "FETCH_TRANSPORTATION_SIZES";
export const FETCH_TRANSPORTATION_SIZES_SUCCESS = "FETCH_TRANSPORTATION_SIZES_SUCCESS";
export const FETCH_TRANSPORTATION_SIZES_FAIL = "FETCH_TRANSPORTATION_SIZES_FAIL";

export const CREATE_TRANSPORTATION_SIZE = "CREATE_TRANSPORTATION_SIZE";
export const CREATE_TRANSPORTATION_SIZE_SUCCESS = "CREATE_TRANSPORTATION_SIZE_SUCCESS";
export const CREATE_TRANSPORTATION_SIZE_FAIL = "CREATE_TRANSPORTATION_SIZE_FAIL";

export const UPDATE_TRANSPORTATION_SIZE = "UPDATE_TRANSPORTATION_SIZE";
export const UPDATE_TRANSPORTATION_SIZE_SUCCESS = "UPDATE_TRANSPORTATION_SIZE_SUCCESS";
export const UPDATE_TRANSPORTATION_SIZE_FAIL = "UPDATE_TRANSPORTATION_SIZE_FAIL";

export const DELETE_TRANSPORTATION_SIZE = "DELETE_TRANSPORTATION_SIZE";
export const DELETE_TRANSPORTATION_SIZE_SUCCESS = "DELETE_TRANSPORTATION_SIZE_SUCCESS";
export const DELETE_TRANSPORTATION_SIZE_FAIL = "DELETE_TRANSPORTATION_SIZE_FAIL";