// path: src/store/TravelAgents/actionTypes.js
export const FETCH_TRAVEL_AGENTS = "FETCH_TRAVEL_AGENTS";
export const FETCH_TRAVEL_AGENTS_SUCCESS = "FETCH_TRAVEL_AGENTS_SUCCESS";
export const FETCH_TRAVEL_AGENTS_FAIL = "FETCH_TRAVEL_AGENTS_FAIL";

export const FETCH_TRAVEL_AGENT = "FETCH_TRAVEL_AGENT";
export const FETCH_TRAVEL_AGENT_SUCCESS = "FETCH_TRAVEL_AGENT_SUCCESS";
export const FETCH_TRAVEL_AGENT_FAIL = "FETCH_TRAVEL_AGENT_FAIL";

export const CREATE_TRAVEL_AGENT = "CREATE_TRAVEL_AGENT";
export const CREATE_TRAVEL_AGENT_SUCCESS = "CREATE_TRAVEL_AGENT_SUCCESS";
export const CREATE_TRAVEL_AGENT_FAIL = "CREATE_TRAVEL_AGENT_FAIL";

export const UPDATE_TRAVEL_AGENT = "UPDATE_TRAVEL_AGENT";
export const UPDATE_TRAVEL_AGENT_SUCCESS = "UPDATE_TRAVEL_AGENT_SUCCESS";
export const UPDATE_TRAVEL_AGENT_FAIL = "UPDATE_TRAVEL_AGENT_FAIL";

export const DELETE_TRAVEL_AGENT = "DELETE_TRAVEL_AGENT";
export const DELETE_TRAVEL_AGENT_SUCCESS = "DELETE_TRAVEL_AGENT_SUCCESS";
export const DELETE_TRAVEL_AGENT_FAIL = "DELETE_TRAVEL_AGENT_FAIL";

export const FETCH_TRAVEL_AGENTS_LOOKUPS = "FETCH_TRAVEL_AGENTS_LOOKUPS";
export const FETCH_TRAVEL_AGENTS_LOOKUPS_SUCCESS = "FETCH_TRAVEL_AGENTS_LOOKUPS_SUCCESS";
export const FETCH_TRAVEL_AGENTS_LOOKUPS_FAIL = "FETCH_TRAVEL_AGENTS_LOOKUPS_FAIL";