// path: src/store/Quotations/actionTypes.js
export const FETCH_QUOTATIONS = "FETCH_QUOTATIONS";
export const FETCH_QUOTATIONS_SUCCESS = "FETCH_QUOTATIONS_SUCCESS";
export const FETCH_QUOTATIONS_FAIL = "FETCH_QUOTATIONS_FAIL";

export const FETCH_QUOTATION = "FETCH_QUOTATION";
export const FETCH_QUOTATION_SUCCESS = "FETCH_QUOTATION_SUCCESS";
export const FETCH_QUOTATION_FAIL = "FETCH_QUOTATION_FAIL";

export const CREATE_QUOTATION = "CREATE_QUOTATION";
export const CREATE_QUOTATION_SUCCESS = "CREATE_QUOTATION_SUCCESS";
export const CREATE_QUOTATION_FAIL = "CREATE_QUOTATION_FAIL";

export const UPDATE_QUOTATION = "UPDATE_QUOTATION";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_FAIL = "UPDATE_QUOTATION_FAIL";

export const DELETE_QUOTATION = "DELETE_QUOTATION";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAIL = "DELETE_QUOTATION_FAIL";

export const FETCH_QUOTATIONS_LOOKUPS = "FETCH_QUOTATIONS_LOOKUPS";
export const FETCH_QUOTATIONS_LOOKUPS_SUCCESS = "FETCH_QUOTATIONS_LOOKUPS_SUCCESS";
export const FETCH_QUOTATIONS_LOOKUPS_FAIL = "FETCH_QUOTATIONS_LOOKUPS_FAIL";