// path: src/store/TransportationTypes/actionTypes.js
export const FETCH_TRANSPORTATION_TYPES = "FETCH_TRANSPORTATION_TYPES";
export const FETCH_TRANSPORTATION_TYPES_SUCCESS =
  "FETCH_TRANSPORTATION_TYPES_SUCCESS";
export const FETCH_TRANSPORTATION_TYPES_FAIL =
  "FETCH_TRANSPORTATION_TYPES_FAIL";

export const CREATE_TRANSPORTATION_TYPE = "CREATE_TRANSPORTATION_TYPE";
export const CREATE_TRANSPORTATION_TYPE_SUCCESS =
  "CREATE_TRANSPORTATION_TYPE_SUCCESS";
export const CREATE_TRANSPORTATION_TYPE_FAIL =
  "CREATE_TRANSPORTATION_TYPE_FAIL";

export const UPDATE_TRANSPORTATION_TYPE = "UPDATE_TRANSPORTATION_TYPE";
export const UPDATE_TRANSPORTATION_TYPE_SUCCESS =
  "UPDATE_TRANSPORTATION_TYPE_SUCCESS";
export const UPDATE_TRANSPORTATION_TYPE_FAIL =
  "UPDATE_TRANSPORTATION_TYPE_FAIL";

export const DELETE_TRANSPORTATION_TYPE = "DELETE_TRANSPORTATION_TYPE";
export const DELETE_TRANSPORTATION_TYPE_SUCCESS =
  "DELETE_TRANSPORTATION_TYPE_SUCCESS";
export const DELETE_TRANSPORTATION_TYPE_FAIL =
  "DELETE_TRANSPORTATION_TYPE_FAIL";