// path: src/store/QuotationExtraServices/actionTypes.js
export const FETCH_EXTRA_SERVICES = "FETCH_EXTRA_SERVICES";
export const FETCH_EXTRA_SERVICES_SUCCESS = "FETCH_EXTRA_SERVICES_SUCCESS";
export const FETCH_EXTRA_SERVICES_FAIL = "FETCH_EXTRA_SERVICES_FAIL";

export const FETCH_QUOTATION_EXTRA_SERVICES = "FETCH_QUOTATION_EXTRA_SERVICES";
export const FETCH_QUOTATION_EXTRA_SERVICES_SUCCESS =
  "FETCH_QUOTATION_EXTRA_SERVICES_SUCCESS";
export const FETCH_QUOTATION_EXTRA_SERVICES_FAIL =
  "FETCH_QUOTATION_EXTRA_SERVICES_FAIL";

export const SAVE_QUOTATION_EXTRA_SERVICES = "SAVE_QUOTATION_EXTRA_SERVICES";
export const SAVE_QUOTATION_EXTRA_SERVICES_SUCCESS =
  "SAVE_QUOTATION_EXTRA_SERVICES_SUCCESS";
export const SAVE_QUOTATION_EXTRA_SERVICES_FAIL =
  "SAVE_QUOTATION_EXTRA_SERVICES_FAIL";

export const CREATE_QUOTATION_EXTRA_SERVICE = "CREATE_QUOTATION_EXTRA_SERVICE";
export const CREATE_QUOTATION_EXTRA_SERVICE_SUCCESS =
  "CREATE_QUOTATION_EXTRA_SERVICE_SUCCESS";
export const CREATE_QUOTATION_EXTRA_SERVICE_FAIL =
  "CREATE_QUOTATION_EXTRA_SERVICE_FAIL";

export const UPDATE_QUOTATION_EXTRA_SERVICE = "UPDATE_QUOTATION_EXTRA_SERVICE";
export const UPDATE_QUOTATION_EXTRA_SERVICE_SUCCESS =
  "UPDATE_QUOTATION_EXTRA_SERVICE_SUCCESS";
export const UPDATE_QUOTATION_EXTRA_SERVICE_FAIL =
  "UPDATE_QUOTATION_EXTRA_SERVICE_FAIL";

export const DELETE_QUOTATION_EXTRA_SERVICE = "DELETE_QUOTATION_EXTRA_SERVICE";
export const DELETE_QUOTATION_EXTRA_SERVICE_SUCCESS =
  "DELETE_QUOTATION_EXTRA_SERVICE_SUCCESS";
export const DELETE_QUOTATION_EXTRA_SERVICE_FAIL =
  "DELETE_QUOTATION_EXTRA_SERVICE_FAIL";

export const RESET_QUOTATION_EXTRA_SERVICES_STATE =
  "RESET_QUOTATION_EXTRA_SERVICES_STATE";
