// path: src/store/QuotationAccumidation/actionTypes.js
export const FETCH_QUOTATION_ACCUMIDATION = "FETCH_QUOTATION_ACCUMIDATION";
export const FETCH_QUOTATION_ACCUMIDATION_SUCCESS = "FETCH_QUOTATION_ACCUMIDATION_SUCCESS";
export const FETCH_QUOTATION_ACCUMIDATION_FAIL = "FETCH_QUOTATION_ACCUMIDATION_FAIL";

export const CREATE_QUOTATION_ACCUMIDATION = "CREATE_QUOTATION_ACCUMIDATION";
export const CREATE_QUOTATION_ACCUMIDATION_SUCCESS = "CREATE_QUOTATION_ACCUMIDATION_SUCCESS";
export const CREATE_QUOTATION_ACCUMIDATION_FAIL = "CREATE_QUOTATION_ACCUMIDATION_FAIL";

export const UPDATE_QUOTATION_ACCUMIDATION = "UPDATE_QUOTATION_ACCUMIDATION";
export const UPDATE_QUOTATION_ACCUMIDATION_SUCCESS = "UPDATE_QUOTATION_ACCUMIDATION_SUCCESS";
export const UPDATE_QUOTATION_ACCUMIDATION_FAIL = "UPDATE_QUOTATION_ACCUMIDATION_FAIL";

export const RESET_QUOTATION_ACCUMIDATION = "RESET_QUOTATION_ACCUMIDATION";