// path: src/store/QuotationPricing/actionTypes.js
export const FETCH_QUOTATION_PRICING_QUEUE = "FETCH_QUOTATION_PRICING_QUEUE";
export const FETCH_QUOTATION_PRICING_QUEUE_SUCCESS =
  "FETCH_QUOTATION_PRICING_QUEUE_SUCCESS";
export const FETCH_QUOTATION_PRICING_QUEUE_FAIL =
  "FETCH_QUOTATION_PRICING_QUEUE_FAIL";

export const FETCH_QUOTATION_PRICING = "FETCH_QUOTATION_PRICING";
export const FETCH_QUOTATION_PRICING_SUCCESS =
  "FETCH_QUOTATION_PRICING_SUCCESS";
export const FETCH_QUOTATION_PRICING_FAIL = "FETCH_QUOTATION_PRICING_FAIL";

export const SET_QUOTATION_PRICING_FILTER = "SET_QUOTATION_PRICING_FILTER";

export const SEND_QUOTATION_FOR_PRICING = "SEND_QUOTATION_FOR_PRICING";
export const SEND_QUOTATION_FOR_PRICING_SUCCESS =
  "SEND_QUOTATION_FOR_PRICING_SUCCESS";
export const SEND_QUOTATION_FOR_PRICING_FAIL =
  "SEND_QUOTATION_FOR_PRICING_FAIL";

export const CANCEL_QUOTATION_PRICING = "CANCEL_QUOTATION_PRICING";
export const CANCEL_QUOTATION_PRICING_SUCCESS =
  "CANCEL_QUOTATION_PRICING_SUCCESS";
export const CANCEL_QUOTATION_PRICING_FAIL =
  "CANCEL_QUOTATION_PRICING_FAIL";

export const UPDATE_QUOTATION_PRICING_PROFIT =
  "UPDATE_QUOTATION_PRICING_PROFIT";
export const UPDATE_QUOTATION_PRICING_PROFIT_SUCCESS =
  "UPDATE_QUOTATION_PRICING_PROFIT_SUCCESS";
export const UPDATE_QUOTATION_PRICING_PROFIT_FAIL =
  "UPDATE_QUOTATION_PRICING_PROFIT_FAIL";

export const APPROVE_QUOTATION_PRICING = "APPROVE_QUOTATION_PRICING";
export const APPROVE_QUOTATION_PRICING_SUCCESS =
  "APPROVE_QUOTATION_PRICING_SUCCESS";
export const APPROVE_QUOTATION_PRICING_FAIL =
  "APPROVE_QUOTATION_PRICING_FAIL";

export const REJECT_QUOTATION_PRICING = "REJECT_QUOTATION_PRICING";
export const REJECT_QUOTATION_PRICING_SUCCESS =
  "REJECT_QUOTATION_PRICING_SUCCESS";
export const REJECT_QUOTATION_PRICING_FAIL = "REJECT_QUOTATION_PRICING_FAIL";