export const FETCH_RESERVATION_FILES = "FETCH_RESERVATION_FILES";
export const FETCH_RESERVATION_FILES_SUCCESS = "FETCH_RESERVATION_FILES_SUCCESS";
export const FETCH_RESERVATION_FILES_FAIL = "FETCH_RESERVATION_FILES_FAIL";

export const FETCH_RESERVATION_FILE = "FETCH_RESERVATION_FILE";
export const FETCH_RESERVATION_FILE_SUCCESS = "FETCH_RESERVATION_FILE_SUCCESS";
export const FETCH_RESERVATION_FILE_FAIL = "FETCH_RESERVATION_FILE_FAIL";

export const CONVERT_QUOTATION_TO_RESERVATION_FILE =
  "CONVERT_QUOTATION_TO_RESERVATION_FILE";
export const CONVERT_QUOTATION_TO_RESERVATION_FILE_SUCCESS =
  "CONVERT_QUOTATION_TO_RESERVATION_FILE_SUCCESS";
export const CONVERT_QUOTATION_TO_RESERVATION_FILE_FAIL =
  "CONVERT_QUOTATION_TO_RESERVATION_FILE_FAIL";
