// path: src/store/Places/actionTypes.js
export const FETCH_PLACES = "FETCH_PLACES";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAIL = "FETCH_PLACES_FAIL";

export const FETCH_PLACE = "FETCH_PLACE";
export const FETCH_PLACE_SUCCESS = "FETCH_PLACE_SUCCESS";
export const FETCH_PLACE_FAIL = "FETCH_PLACE_FAIL";

export const CREATE_PLACE = "CREATE_PLACE";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const CREATE_PLACE_FAIL = "CREATE_PLACE_FAIL";

export const UPDATE_PLACE = "UPDATE_PLACE";
export const UPDATE_PLACE_SUCCESS = "UPDATE_PLACE_SUCCESS";
export const UPDATE_PLACE_FAIL = "UPDATE_PLACE_FAIL";

export const DELETE_PLACE = "DELETE_PLACE";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const DELETE_PLACE_FAIL = "DELETE_PLACE_FAIL";

export const FETCH_PLACES_LOOKUPS = "FETCH_PLACES_LOOKUPS";
export const FETCH_PLACES_LOOKUPS_SUCCESS = "FETCH_PLACES_LOOKUPS_SUCCESS";
export const FETCH_PLACES_LOOKUPS_FAIL = "FETCH_PLACES_LOOKUPS_FAIL";