// path: src/store/Restaurants/actionTypes.js
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_RESTAURANTS_SUCCESS = "FETCH_RESTAURANTS_SUCCESS";
export const FETCH_RESTAURANTS_FAIL = "FETCH_RESTAURANTS_FAIL";

export const FETCH_RESTAURANT = "FETCH_RESTAURANT";
export const FETCH_RESTAURANT_SUCCESS = "FETCH_RESTAURANT_SUCCESS";
export const FETCH_RESTAURANT_FAIL = "FETCH_RESTAURANT_FAIL";

export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";

export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAIL = "UPDATE_RESTAURANT_FAIL";

export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";

export const FETCH_RESTAURANTS_LOOKUPS = "FETCH_RESTAURANTS_LOOKUPS";
export const FETCH_RESTAURANTS_LOOKUPS_SUCCESS =
  "FETCH_RESTAURANTS_LOOKUPS_SUCCESS";
export const FETCH_RESTAURANTS_LOOKUPS_FAIL = "FETCH_RESTAURANTS_LOOKUPS_FAIL";

export const FETCH_MEALS = "FETCH_MEALS";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_FAIL = "FETCH_MEALS_FAIL";

export const CREATE_MEAL = "CREATE_MEAL";
export const CREATE_MEAL_SUCCESS = "CREATE_MEAL_SUCCESS";
export const CREATE_MEAL_FAIL = "CREATE_MEAL_FAIL";

export const UPDATE_MEAL = "UPDATE_MEAL";
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS";
export const UPDATE_MEAL_FAIL = "UPDATE_MEAL_FAIL";

export const DELETE_MEAL = "DELETE_MEAL";
export const DELETE_MEAL_SUCCESS = "DELETE_MEAL_SUCCESS";
export const DELETE_MEAL_FAIL = "DELETE_MEAL_FAIL";
