// path: src/store/Guides/actionTypes.js
export const FETCH_GUIDES = "FETCH_GUIDES";
export const FETCH_GUIDES_SUCCESS = "FETCH_GUIDES_SUCCESS";
export const FETCH_GUIDES_FAIL = "FETCH_GUIDES_FAIL";

export const FETCH_GUIDE = "FETCH_GUIDE";
export const FETCH_GUIDE_SUCCESS = "FETCH_GUIDE_SUCCESS";
export const FETCH_GUIDE_FAIL = "FETCH_GUIDE_FAIL";

export const CREATE_GUIDE = "CREATE_GUIDE";
export const CREATE_GUIDE_SUCCESS = "CREATE_GUIDE_SUCCESS";
export const CREATE_GUIDE_FAIL = "CREATE_GUIDE_FAIL";

export const UPDATE_GUIDE = "UPDATE_GUIDE";
export const UPDATE_GUIDE_SUCCESS = "UPDATE_GUIDE_SUCCESS";
export const UPDATE_GUIDE_FAIL = "UPDATE_GUIDE_FAIL";

export const DELETE_GUIDE = "DELETE_GUIDE";
export const DELETE_GUIDE_SUCCESS = "DELETE_GUIDE_SUCCESS";
export const DELETE_GUIDE_FAIL = "DELETE_GUIDE_FAIL";

export const FETCH_GUIDE_LANGUAGES = "FETCH_GUIDE_LANGUAGES";
export const FETCH_GUIDE_LANGUAGES_SUCCESS = "FETCH_GUIDE_LANGUAGES_SUCCESS";
export const FETCH_GUIDE_LANGUAGES_FAIL = "FETCH_GUIDE_LANGUAGES_FAIL";