// path: src/store/listItems/actionTypes.js
export const FETCH_LIST_ITEMS = "FETCH_LIST_ITEMS";
export const FETCH_LIST_ITEMS_SUCCESS = "FETCH_LIST_ITEMS_SUCCESS";
export const FETCH_LIST_ITEMS_FAIL = "FETCH_LIST_ITEMS_FAIL";

export const CREATE_LIST_ITEM = "CREATE_LIST_ITEM";
export const CREATE_LIST_ITEM_SUCCESS = "CREATE_LIST_ITEM_SUCCESS";
export const CREATE_LIST_ITEM_FAIL = "CREATE_LIST_ITEM_FAIL";

export const UPDATE_LIST_ITEM = "UPDATE_LIST_ITEM";
export const UPDATE_LIST_ITEM_SUCCESS = "UPDATE_LIST_ITEM_SUCCESS";
export const UPDATE_LIST_ITEM_FAIL = "UPDATE_LIST_ITEM_FAIL";

export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM";
export const DELETE_LIST_ITEM_SUCCESS = "DELETE_LIST_ITEM_SUCCESS";
export const DELETE_LIST_ITEM_FAIL = "DELETE_LIST_ITEM_FAIL";

export const RESET_LIST_ITEMS_FLAGS = "RESET_LIST_ITEMS_FLAGS";