// path: src/store/Hotels/actionTypes.js
export const FETCH_HOTELS = "FETCH_HOTELS";
export const FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS";
export const FETCH_HOTELS_FAIL = "FETCH_HOTELS_FAIL";

export const FETCH_HOTEL = "FETCH_HOTEL";
export const FETCH_HOTEL_SUCCESS = "FETCH_HOTEL_SUCCESS";
export const FETCH_HOTEL_FAIL = "FETCH_HOTEL_FAIL";

export const CREATE_HOTEL = "CREATE_HOTEL";
export const CREATE_HOTEL_SUCCESS = "CREATE_HOTEL_SUCCESS";
export const CREATE_HOTEL_FAIL = "CREATE_HOTEL_FAIL";

export const UPDATE_HOTEL = "UPDATE_HOTEL";
export const UPDATE_HOTEL_SUCCESS = "UPDATE_HOTEL_SUCCESS";
export const UPDATE_HOTEL_FAIL = "UPDATE_HOTEL_FAIL";

export const DELETE_HOTEL = "DELETE_HOTEL";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL";

// Lookups (list-items)
export const FETCH_HOTELS_LOOKUPS = "FETCH_HOTELS_LOOKUPS";
export const FETCH_HOTELS_LOOKUPS_SUCCESS = "FETCH_HOTELS_LOOKUPS_SUCCESS";
export const FETCH_HOTELS_LOOKUPS_FAIL = "FETCH_HOTELS_LOOKUPS_FAIL";

// Season rates
export const FETCH_SEASON_RATES = "FETCH_SEASON_RATES";
export const FETCH_SEASON_RATES_SUCCESS = "FETCH_SEASON_RATES_SUCCESS";
export const FETCH_SEASON_RATES_FAIL = "FETCH_SEASON_RATES_FAIL";

export const CREATE_SEASON_RATE = "CREATE_SEASON_RATE";
export const CREATE_SEASON_RATE_SUCCESS = "CREATE_SEASON_RATE_SUCCESS";
export const CREATE_SEASON_RATE_FAIL = "CREATE_SEASON_RATE_FAIL";

export const UPDATE_SEASON_RATE = "UPDATE_SEASON_RATE";
export const UPDATE_SEASON_RATE_SUCCESS = "UPDATE_SEASON_RATE_SUCCESS";
export const UPDATE_SEASON_RATE_FAIL = "UPDATE_SEASON_RATE_FAIL";

export const DELETE_SEASON_RATE = "DELETE_SEASON_RATE";
export const DELETE_SEASON_RATE_SUCCESS = "DELETE_SEASON_RATE_SUCCESS";
export const DELETE_SEASON_RATE_FAIL = "DELETE_SEASON_RATE_FAIL";