// path: src/store/QuotationDays/actionTypes.js
export const FETCH_QUOTATION_DAYS = "FETCH_QUOTATION_DAYS";
export const FETCH_QUOTATION_DAYS_SUCCESS = "FETCH_QUOTATION_DAYS_SUCCESS";
export const FETCH_QUOTATION_DAYS_FAIL = "FETCH_QUOTATION_DAYS_FAIL";

export const FETCH_QUOTATION_DAY_LOOKUPS = "FETCH_QUOTATION_DAY_LOOKUPS";
export const FETCH_QUOTATION_DAY_LOOKUPS_SUCCESS = "FETCH_QUOTATION_DAY_LOOKUPS_SUCCESS";
export const FETCH_QUOTATION_DAY_LOOKUPS_FAIL = "FETCH_QUOTATION_DAY_LOOKUPS_FAIL";

export const FETCH_RESTAURANT_MEALS = "FETCH_RESTAURANT_MEALS";
export const FETCH_RESTAURANT_MEALS_SUCCESS = "FETCH_RESTAURANT_MEALS_SUCCESS";
export const FETCH_RESTAURANT_MEALS_FAIL = "FETCH_RESTAURANT_MEALS_FAIL";

export const CREATE_QUOTATION_DAY = "CREATE_QUOTATION_DAY";
export const CREATE_QUOTATION_DAY_SUCCESS = "CREATE_QUOTATION_DAY_SUCCESS";
export const CREATE_QUOTATION_DAY_FAIL = "CREATE_QUOTATION_DAY_FAIL";

export const UPDATE_QUOTATION_DAY = "UPDATE_QUOTATION_DAY";
export const UPDATE_QUOTATION_DAY_SUCCESS = "UPDATE_QUOTATION_DAY_SUCCESS";
export const UPDATE_QUOTATION_DAY_FAIL = "UPDATE_QUOTATION_DAY_FAIL";

export const RESET_QUOTATION_DAY_STATE = "RESET_QUOTATION_DAY_STATE";