// path: src/store/TransportationCompanies/actionTypes.js
export const FETCH_TRANSPORTATION_COMPANIES = "FETCH_TRANSPORTATION_COMPANIES";
export const FETCH_TRANSPORTATION_COMPANIES_SUCCESS = "FETCH_TRANSPORTATION_COMPANIES_SUCCESS";
export const FETCH_TRANSPORTATION_COMPANIES_FAIL = "FETCH_TRANSPORTATION_COMPANIES_FAIL";

export const FETCH_TRANSPORTATION_COMPANY = "FETCH_TRANSPORTATION_COMPANY";
export const FETCH_TRANSPORTATION_COMPANY_SUCCESS = "FETCH_TRANSPORTATION_COMPANY_SUCCESS";
export const FETCH_TRANSPORTATION_COMPANY_FAIL = "FETCH_TRANSPORTATION_COMPANY_FAIL";

export const CREATE_TRANSPORTATION_COMPANY = "CREATE_TRANSPORTATION_COMPANY";
export const CREATE_TRANSPORTATION_COMPANY_SUCCESS = "CREATE_TRANSPORTATION_COMPANY_SUCCESS";
export const CREATE_TRANSPORTATION_COMPANY_FAIL = "CREATE_TRANSPORTATION_COMPANY_FAIL";

export const UPDATE_TRANSPORTATION_COMPANY = "UPDATE_TRANSPORTATION_COMPANY";
export const UPDATE_TRANSPORTATION_COMPANY_SUCCESS = "UPDATE_TRANSPORTATION_COMPANY_SUCCESS";
export const UPDATE_TRANSPORTATION_COMPANY_FAIL = "UPDATE_TRANSPORTATION_COMPANY_FAIL";

export const DELETE_TRANSPORTATION_COMPANY = "DELETE_TRANSPORTATION_COMPANY";
export const DELETE_TRANSPORTATION_COMPANY_SUCCESS = "DELETE_TRANSPORTATION_COMPANY_SUCCESS";
export const DELETE_TRANSPORTATION_COMPANY_FAIL = "DELETE_TRANSPORTATION_COMPANY_FAIL";

export const FETCH_TRANSPORTATION_LOOKUPS = "FETCH_TRANSPORTATION_LOOKUPS";
export const FETCH_TRANSPORTATION_LOOKUPS_SUCCESS = "FETCH_TRANSPORTATION_LOOKUPS_SUCCESS";
export const FETCH_TRANSPORTATION_LOOKUPS_FAIL = "FETCH_TRANSPORTATION_LOOKUPS_FAIL";

export const UPSERT_TRANSPORTATION_RATES = "UPSERT_TRANSPORTATION_RATES";
export const UPSERT_TRANSPORTATION_RATES_SUCCESS = "UPSERT_TRANSPORTATION_RATES_SUCCESS";
export const UPSERT_TRANSPORTATION_RATES_FAIL = "UPSERT_TRANSPORTATION_RATES_FAIL";

export const DELETE_TRANSPORTATION_RATE = "DELETE_TRANSPORTATION_RATE";
export const DELETE_TRANSPORTATION_RATE_SUCCESS = "DELETE_TRANSPORTATION_RATE_SUCCESS";
export const DELETE_TRANSPORTATION_RATE_FAIL = "DELETE_TRANSPORTATION_RATE_FAIL";